### ISSUE TITLE
Stop the correct controllers

### ISSUE THREAD

**Issue by shadowmanos** [shadow-robot/sr-visualization#32]
When using the controller change GUI all the loaded controllers are stopped before started the selected ones. Thus the GUI stops controllers that it is not to meant to handle for example a ronex passthrough running in the same loop as the hand. The GUI source code should maintain a list of controllers that it handles and only stop those.

**Comment by markpitchless** [comment]
Should probably use the param server to store the set of controlled controllers so it can be configured if needed.

**Comment by shadowmanos** [comment]
fixed in indigo-devel
