### ISSUE TITLE
installing deleted folder

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/sr-visualization#37]
in the F_hand_driver_prefix branch, model folder was deleted and should not be installed

<pre>
sr_gui_joint_slider/CMakeLists.txt
@@ -12,6 +12,4 @@ catkin_python_setup()
 
 install( DIRECTORY uis DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} )
 
-install( DIRECTORY model DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} )
-
-install( FILES sr_joint_slider_plugin.xml DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} )
\ No newline at end of file
+install( FILES sr_joint_slider_plugin.xml DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} )
</pre>

**Comment by toliver** [comment]
Thanks for that.
About the F_hand_driver_prefix branch, please bear in mind that only the change_controllers and joint_slider plugins have been adapted for the moment.

**Comment by guihomework** [comment]
Thanks for the notice, I went on this branch to get the change_controllers and sliders mainly. I think detected a bug too, I will open an issue for that.
A next nice to have could be joint_calibration and motor tuning which we use once every two or three months
