### ISSUE TITLE
Convert grasp GUI to new grasp format

### ISSUE THREAD

**Issue by markpitchless** [shadow-robot/sr-visualization#39]
https://github.com/shadow-robot/sr-visualization/tree/indigo-devel/sr_gui_grasp_controller

Convert this to use moveit_msgs/Grasp, sored as YAML instead of it's own XML format. Have it use the grasp node or grasp controller to run the grasp.

Update both save and send.

1d

**Comment by ugocupcic** [comment]
Use the moveit database instead of yaml stored grasps. 

Save if write access to the db.
