### ISSUE TITLE
Rearrange shadow plugin sub-menus

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-visualization#48]
@jlaforga points out that Change Controllers plugin is a bit confusing for the user, whereas Teach Mode plugin is easier.

We probably should create a `basic` and an `advanced` submenus under Shadow Robot.

To do this is enough to add a group tag in the `..._plugin.xml` e.g:

https://github.com/shadow-robot/sr-visualization/blob/indigo-devel/sr_gui_teach_mode/sr_teach_mode_plugin.xml

**Comment by adelarosat** [comment]
I don't know if we have to add a third level of submenus. Simply renaming "Teach Mode" to "Change Controllers", and change the old "Change Controllers" to "Advanced Control" should suffice.

**Comment by toliver** [comment]
The name change looks good to me. But I think that a rearrange under basic and advanced would help, as currently we have around 15 plugins, and a new user probably only needs 2 or 3 of them to move the hand. This would help avoid confusion.

**Comment by adelarosat** [comment]
That's fine.

**Comment by ugocupcic** [comment]
@adelarosat @jlaforga this is what we think would make the most sense:

no category (directly under shadow robot):
- teach mode (with renaming, so would be **change controllers**)
- sliders
- grasp

basic:
- motor reset
- calibration
- controller tuner

advanced
- biotacs
- bootloader
- change controllers (with renaming so would be **advanced control**)
- change muscle controllers
- cyberglove
- movement recorder
- muscle driver bootloader
- self test

**Comment by ugocupcic** [comment]
Doing the name change in another pr for more simplicity
https://github.com/shadow-robot/sr-visualization/issues/68
